bindkey "^[^[[D" backward-word
bindkey "^[^[[C" forward-word

eval "$(brew shellenv)"
fpath=($HOMEBREW_PREFIX/share/zsh/site-functions $fpath)

. ~/.asdf/plugins/java/set-java-home.zsh

. /opt/homebrew/opt/asdf/libexec/asdf.sh

# Automatically installed by iterm2 into .zshrc
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh" || true

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/Craig/tools/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/Craig/tools/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/Craig/tools/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/Craig/tools/google-cloud-sdk/completion.zsh.inc'; fi
