set dotenv-filename := ".envrc"

import ".just/console.just"
import ".just/git.just"
import ".just/git-rebase.just"
import ".just/git-test.just"

# `just --list --unsorted --global-justfile`
[group('default')]
default:
    @just --list --unsorted --global-justfile

# Count lines of code
[group('default')]
scc:
    #!/usr/bin/env bash
    shopt -s globstar
    scc **/src/{main,test}

# Override this with a command called `woof` which notifies you in whatever ways you prefer.
# My `woof` command uses `echo`, `say`, and sends a Pushover notification.
echo_command := env('ECHO_COMMAND', "echo")
