[tools]
bun = "latest"
java = "temurin"
maven = "3.9.12"
mvnd = "1.0.5"
"npm:@openai/codex" = "latest"
node = "24.13.0"
"npm:@google/gemini-cli" = "latest"
"npm:create-docusaurus" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:oclif" = "latest"
"npm:oxfmt" = "0.49.0"
"npm:strip-ansi-cli" = "latest"
"npm:trash" = "latest"
"npm:trash-cli" = "latest"
rust = "nightly"

[settings]
idiomatic_version_file_enable_tools = ["node"]
