[tools]
bun = "latest"
java = "temurin"
maven = "3.9.16"
mvnd = "1.0.6"
"npm:@openai/codex" = "latest"
node = "26.5.1"
"npm:@google/gemini-cli" = "0.53.0"
"npm:create-docusaurus" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:oclif" = "latest"
"npm:oxfmt" = "0.61.0"
"npm:strip-ansi-cli" = "latest"
"npm:trash" = "latest"
"npm:trash-cli" = "latest"
rust = "nightly"

[settings]
idiomatic_version_file_enable_tools = ["node"]
