[tools]
bun = "1.4.0"
herdr = "0.8.2"
java = "temurin-26.0.2+10"
maven = "3.9.16"
mvnd = "1.0.6"
"npm:@openai/codex" = "0.153.4"
node = "26.8.1"
"npm:@google/gemini-cli" = "0.57.0"
"npm:create-docusaurus" = "3.10.2"
"npm:markdownlint-cli2" = "0.23.2"
"npm:oclif" = "4.24.0"
"npm:oxfmt" = "0.65.0"
"npm:strip-ansi-cli" = "4.0.0"
"npm:trash" = "10.1.1"
"npm:trash-cli" = "7.2.0"
rust = "1.98.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
